sonar.projectKey=codeartstest
sonar.organization=codeartstest
sonar.sources=backend/src,frontend/src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/__pycache__/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.cpd.exclusions=frontend/src/data/**